### ISSUE TITLE
ToDo issues list. 

### ISSUE THREAD

**Issue by L0rd1k** [L0rd1k/SageEngine#2]
- [x] Remove loading shaders from file.
- [x] Add doxygen documentation
- [x] Create project's diagram architecture.
